apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=Dockerfile"
    - "--context=git://github.com/AlperanK/test-cicd.git"
    - "--destination=harbor.taas.vodafone.local/taas-test/deneme:v1"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: docker-cred
      items:
        - key: .dockerconfigjson
          path: config.json
