trigger:
  branches:
    include:
      - main  # Change this to your desired branch

pool:
  name: 'tzl-poc'
  demands:
     - agent.name -equals tzl-poc-ado-newagent-6548857799-2pnk8

steps:
  
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'taaspoc-afk'
    namespace: 'default'
    command: 'get'
    arguments: 'pods'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Container Registry'
    versionSpec: '1.27.3'
    outputFormat: 'none'
  
#    secretType: 'dockerRegistry'
#    containerRegistryType: 'Azure Container Registry'
#    secretType: 'dockerRegistry'
#    containerRegistryType: 'Azure Container Registry'
#- task: Docker@2
#  displayName: 'Build and push Docker image'
#  inputs:
#    command: 'buildAndPush'
#    containerRegistry: 'dockerafk'  # Use the service connection name you created earlier
#    repository: 'alperanfk/cicd'  # Replace with your Docker Hub username and image repository name
#    Dockerfile: '**/Dockerfile'  # Path to your Dockerfile
