trigger:
  branches:
    include:
      - main  # Replace 'main' with the branch you want to trigger the pipeline from

pool:
  vmImage: 'ubuntu-latest'  # You can change the VM image as per your requirement
  name: "tzl-poc"

steps:
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'harbortaas'  # The name of your Harbor service connection
    repository: 'tzl-shrd-harbor.taas.vodafone.local/test-2'  # Full URL of your Harbor registry and the repository name
    command: 'build'
    Dockerfile: 'Dockerfile'  # Relative path to the Dockerfile (same directory as the YAML)

- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    containerRegistry: 'harbortaas'  # The name of your Harbor service connection
    repository: 'tzl-shrd-harbor.taas.vodafone.local/test-2'  # Full URL of your Harbor registry and the repository name
    command: 'push'
