trigger:
  branches:
    include:
      - main  # Change this to your desired branch

pool:
  vmImage: 'ubuntu-latest'
  pool: 'test'

steps:
- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'dockerafk'  # Use the service connection name you created earlier
    repository: 'alperanfk/cicd'  # Replace with your Docker Hub username and image repository name
    Dockerfile: '**/Dockerfile'  # Path to your Dockerfile
