
trigger:
-master

steps:
 - task: SonarQubePrepare@5
   inputs:
     SonarQube: 'sonar-furkan-deneme'
     scannerMode: 'CLI'
     configMode: 'manual'
     cliProjectKey: 'sonar-furkan-deneme'

- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'




















#trigger:
#  branches:
#    include:
#      - main  # Change this to your desired branch
#
#pool:
#  name: 'tzl-wl'
#
#
#steps:
#- task: Kubernetes@1
#  inputs:
#    connectionType: 'Kubernetes Service Connection'
#    kubernetesServiceEndpoint: 'tzlpoc'
#    command: 'apply'
#    arguments: '-f kaniko.yml'
#    secretType: 'dockerRegistry'
#    containerRegistryType: 'Azure Container Registry'
#    outputFormat: 'none'
 
#- task: Kubernetes@1
#  inputs:
#    connectionType: 'Kubernetes Service Connection'
#    kubernetesServiceEndpoint: 'tzlpoc-svc'
#    namespace: 'default'
#    command: 'get'
#    useConfigurationFile: true
#    configuration: '/usr/local/bin/kubectl'
#    arguments: 'pods'
#    secretType: 'dockerRegistry'
#    containerRegistryType: 'Container Registry'
#    versionSpec: '1.27.3'
#    outputFormat: 'none'
  
#    secretType: 'dockerRegistry'
#    containerRegistryType: 'Azure Container Registry'
#    secretType: 'dockerRegistry'
#    containerRegistryType: 'Azure Container Registry'
#- task: Docker@2
#  displayName: 'Build and push Docker image'
#  inputs:
#    command: 'buildAndPush'
#    containerRegistry: 'dockerafk'  # Use the service connection name you created earlier
#    repository: 'alperanfk/cicd'  # Replace with your Docker Hub username and image repository name
#    Dockerfile: '**/Dockerfile'  # Path to your Dockerfile
